cook_book/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'', include(('cook_book_app.urls', 'cook_book_app'), 
    namespace='cook_book_app')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
]

cook_book_app/urls.py
from django.conf.urls import url 
from . import views 

urlpatterns = [     
    # Strona główna.    
    url(r'^$', views.index, name='index'), 
    url(r'^all_dish/$', views.all_dish, name='all_dish'),
    url(r'^all_dish/(?P<dish_id>\d+)/$', views.dish, name='dish'),
    url(r'^new_dish/$', views.new_dish, name='new_dish'),
    url(r'^new_recipe/(?P<dish_id>\d+)/$', views.new_recipe,
    name='new_recipe'),
    url(r'^edit_recipe/(?P<recipe_id>\d+)/$', views.edit_recipe, 
    name='edit_recipe'),
]

users/urls.py
from django.conf.urls import url 
from django.contrib.auth.views import LoginView 
from . import views

urlpatterns = [    
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'),
    name='login'), 
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

cook_book_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Dish(models.Model):
    """Potrawa"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.text
        
class Recipe(models.Model):
    """Przepis na potrawę"""
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'recipes'
        
    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

cook_book_app/forms.py
from django import forms
from .models import Dish
from .models import Recipe


class DishForm(forms.ModelForm):     
    class Meta:        
        model = Dish
        fields = ['text']         
        labels = {'text': ''}

class RecipeForm(forms.ModelForm):    
    class Meta:        
        model = Recipe        
        fields = ['text']        
        labels = {'text': ''}         
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

cook_book_app/views.py
from django.shortcuts import render
from .models import Dish
from .models import Recipe
from django.http import HttpResponseRedirect 
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import DishForm
from .forms import RecipeForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):    
    return render(request, 'cook_book_app/index.html')

@login_required
def all_dish(request):     
    all_dish = Dish.objects.filter(owner=request.user).order_by(
    'date_added')    
    context = {'all_dish': all_dish}     
    return render(request, 'cook_book_app/all_dish.html', context)

@login_required
def dish(request, dish_id):     
    dish = Dish.objects.get(id=dish_id)
    if dish.owner != request.user:         
        raise Http404
        
    recipes = dish.recipe_set.order_by('-date_added')     
    context = {'dish': dish, 'recipes': recipes}     
    return render(request, 'cook_book_app/dish.html', context)

@login_required
def new_dish(request):    
    if request.method != 'POST':         
        form = DishForm()     
    else:        
        form = DishForm(request.POST)         
        if form.is_valid(): 
            new_dish = form.save(commit=False)
            new_dish.owner = request.user           
            form.save()             
            return HttpResponseRedirect(reverse('cook_book_app:all_dish')) 
            
    context = {'form': form}     
    return render(request, 'cook_book_app/new_dish.html', context)

@login_required
def new_recipe(request, dish_id):    
    dish = Dish.objects.get(id=dish_id)
    if request.method != 'POST':         
        form = RecipeForm()     
    else:        
        form = RecipeForm(data=request.POST)         
        if form.is_valid():            
            new_recipe = form.save(commit=False)             
            new_recipe.dish = dish             
            new_recipe.save()            
            return HttpResponseRedirect(reverse('cook_book_app:dish', args=[dish_id]))
            
    context = {'dish': dish, 'form': form}    
    return render(request, 'cook_book_app/new_recipe.html', context)

@login_required
def edit_recipe(request, recipe_id):    
    recipe = Recipe.objects.get(id=recipe_id)     
    dish = recipe.dish
    if dish.owner != request.user:
        raise Http404
    if request.method != 'POST':        
        form = RecipeForm(instance=recipe)     
    else:        
        form = RecipeForm(instance=recipe, data=request.POST)         
        if form.is_valid():            
            form.save()             
            return HttpResponseRedirect(reverse('cook_book_app:dish', args=[dish.id]))
            
    context = {'recipe': recipe, 'dish': dish, 'form': form}    
    return render(request, 'cook_book_app/edit_recipe.html', context)

users/views.py
from django.http import HttpResponseRedirect 
from django.urls import reverse 
from django.contrib.auth import logout
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate 
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('cook_book_app:index'))
    
def register(request):    
    if request.method != 'POST':        
        form = UserCreationForm()     
    else:        
        form = UserCreationForm(data=request.POST) 
        
        if form.is_valid():             
            new_user = form.save()             
            authenticated_user = authenticate(
            username=new_user.username,                 
            password=request.POST['password1'])            
            login(request, authenticated_user)             
            return HttpResponseRedirect(reverse('cook_book_app:index'))
             
    context = {'form': form}    
    return render(request, 'users/register.html', context)

cook_book_app/templates/cook_book_app/all_dish.html
{% extends "cook_book_app/base.html" %}

{% block content %}

  <p>Potrawy</p>
  
  <ul>     
    {% for dish in all_dish %}       
      <li>        
        <a href="{% url 'cook_book_app:dish' dish.id %}">{{ dish }}</a>      
      </li>   
    {% empty %}       
      <li>Nie została jeszcze dodana żadna potrawa.</li>    
    {% endfor %}  
  </ul> 
  
   <a href="{% url 'cook_book_app:new_dish' %}">Dodaj nową potrawę</a>
  
{% endblock content %}

cook_book_app/templates/cook_book_app/base.html
<p>  
  <a href="{% url 'cook_book_app:index' %}">Cookbook</a> -   
  <a href="{% url 'cook_book_app:all_dish' %}">Potrawy</a>
    {% if user.is_authenticated %}     
      Witaj, {{ user.username }}.   
      <a href="{% url 'users:logout' %}">Wyloguj</a>
    {% else %}  
      <a href="{% url 'users:register' %}">Rejestruj</a> -  
      <a href="{% url 'users:login' %}">Zaloguj</a>   
    {% endif %}
</p>

{% block content %}{% endblock content %}

cook_book_app/templates/cook_book_app/dish.html
{% extends 'cook_book_app/base.html' %}

{% block content %}

  <p>Potrawa: {{ dish }}</p> 
  
  <p>Przepisy:</p>  
  <p>
    <a href="{% url 'cook_book_app:new_recipe' dish.id %}">Dodaj nowy przepis</a>
  </p>
  <ul>   
  {% for recipe in recipes %}     
    <li>      
      <p>{{ recipe.date_added|date:'d M Y H:i' }}</p>       
      <p>{{ recipe.text|linebreaks }}</p> 
      <p>        
        <a href="{% url 'cook_book_app:edit_recipe' recipe.id %}">
            Edytuj przepis
        </a>      
      </p>
    </li>  
  {% empty %}     
    <li>      
      Nie ma jeszcze żadnego przepisu.    
    </li>
  {% endfor %}  
  </ul>
  
{% endblock content %}

cook_book_app/templates/cook_book_app/edit_recipe.html
{% extends "cook_book_app/base.html" %}

{% block content %}

  <p>
    <a href="{% url 'cook_book_app:dish' dish.id %}">{{ dish }}</a>
  </p>
  
  <p>Edycja przepisu:</p>
  
  <form action="{% url 'cook_book_app:edit_recipe' recipe.id %}" 
    method='post'>     
    {% csrf_token %}    
    {{ form.as_p }}    
    <button name="submit">Zapisz zmiany</button>   
  </form>
  
{% endblock content %}

cook_book_app/templates/cook_book_app/index.html
{% extends "cook_book_app/base.html" %}

{% block content %}
  <p>Cookbook zawiera przepisy popularnych potraw.</p>
{% endblock content %}

cook_book_app/templates/cook_book_app/new_dish.html
{% extends "cook_book_app/base.html" %}

{% block content %}

  <p>Dodaj nową potrawę:</p>  
  <form action="{% url 'cook_book_app:new_dish' %}" method='post'>     
    {% csrf_token %}     
    {{ form.as_p }}     
    <button name="submit">Dodaj potrawę</button>   
  </form>
  
{% endblock content %}

cook_book_app/templates/cook_book_app/new_recipe.html
{% extends 'cook_book_app/base.html' %}

{% block content %}

  <p><a href="{% url 'cook_book_app:dish' dish.id %}">{{ dish }}</a>
  </p>
  
  <p>Dodaj nowy przepis:</p>
  
  <form action="{% url 'cook_book_app:new_recipe' dish.id %}"
  method='post'>
    {% csrf_token %}
    {{ form.as_p}}
    <button name='submit'>Dodaj przepis</button>
  </form>

{% endblock content %}

users/templates/users/login.html
{% extends "cook_book_app/base.html" %}

{% block content %}

  {% if form.errors %}   
  <p>Nazwa użytkownika i hasło są nieprawidłowe. Proszę spróbować 
  ponownie.</p>  
  {% endif %}
  
  <form method="post" action="{% url 'users:login' %}">   
    {% csrf_token %}  
    {{ form.as_p }} 
    
  <button name="submit">Zaloguj</button>   
  <input type="hidden" name="next" 
  value="{% url 'cook_book_app:index' %}" />   
  </form>
  
{% endblock content %}

users/templates/users/register.html
{% extends "cook_book_app/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">    
    {% csrf_token %}    
    {{ form.as_p }}
    <button name="submit">Rejestruj</button>    
    <input type="hidden" name="next" 
    value="{% url 'cook_book_app:index' %}" />  
  </form>
  
{% endblock content %}